CREATE DATABASE IF NOT EXISTS etsycutioner;

USE etsycutioner;

CREATE TABLE IF NOT EXISTS people (
  id INT NOT NULL AUTO_INCREMENT,
  name TEXT NOT NULL,
  photo TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS shops (
  id INT NOT NULL AUTO_INCREMENT,
  name TEXT NOT NULL,
  reviews_count INT,
  avg_stars_per_cent TINYINT,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS listings (
  id INT NOT NULL AUTO_INCREMENT,
  name TEXT NOT NULL,
  photo TEXT,
  shop INT NOT NULL,

  PRIMARY KEY (id),
  FOREIGN KEY (shop) REFERENCES shops(id)
);

ALTER TABLE listings AUTO_INCREMENT=666666666;

CREATE TABLE IF NOT EXISTS reviews (
  id INT NOT NULL AUTO_INCREMENT,
  person INT NOT NULL,
  shop INT NOT NULL,
  listing INT NOT NULL,
  body TEXT NOT NULL,
  date DATETIME NOT NULL,
  stars TINYINT NOT NULL,

  PRIMARY KEY (id),
  FOREIGN KEY (person) REFERENCES people(id),
  FOREIGN KEY (shop) REFERENCES shops(id),
  FOREIGN KEY (listing) REFERENCES listings(id)
);